language: python
python:
  - 2.6
  - 3.3

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -yqq texlive-latex-base
  - sudo apt-get install -yqq texlive-latex-extra
  - sudo apt-get install -yqq texlive-latex-recommended
  - sudo apt-get install -yqq texlive-fonts-recommended
  - sudo apt-get install -yqq texinfo

install:
  - pip install sphinx

script:
  - make ${TARGET}

env:
  matrix:
    - TARGET=html
    - TARGET=pdf
    - TARGET=check

cache: apt
